### PR TITLE
Update the age in meta tag descriptions

### LINKED ISSUE #76: Change my age to 14 in the meta tag descriptions
**Is your feature request related to a problem? Please describe.**
Currently, my age on meta tag descriptions on index.html file is still 13 years

**Describe the solution you'd like**
Change my age to 14 in the meta tag descriptions in index.html file

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by Keerthivardhan1**
## Purpose
hear the issue is to change the age in the index.html files 
The purpose of this Pull Request is to fix #76

## Goals
 as per the issue the goal is to change the age 13 to 14 in all index.html file 

## Approach
step1:  clone the repo
step2:   read README file and understand  code structure of the project .
step3:  change the age from 13 to 14 in the all index.html files that are the project.
step4:  add and commit the changes and push your branch.
 
##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Test environment
 Chrome 
 Version 106.0.5249.119 (Official Build) (64-bit)

## Learning
 by understanding the project I learnt how to structure our code and divide in to categories

### CODE REVIEW

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
The age in the Facebook OG meta tag description's age in index.html file is 1 years old. @Keerthivardhan1 

image

Change the age in it to 14 years old.

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Remove the Preview Link section in the pr template @Keerthivardhan1

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Remove the screenshots section from the pr template @Keerthivardhan1

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
The age in the light/index.html file Facebook OG meta tag description's age is still 13 years old.

image

Change it to 14 years old @Keerthivardhan1

**Comment by Keerthivardhan1** [comment]
done

**Pull request closed without merging**
