### PR TITLE
Remove unwanted link tag from the contact section

### LINKED ISSUE #154: Remove the unwanted link tag in the contact section
- Currently, there is an unwanted link tag in the contact section
- Remove it

https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE/blob/bbb62296bd27270313436aa40de85fb2fb471136/dark/index.html#L234-L235

### PR DESCRIPTION
**Pull request by Rishav1707**
## Purpose

The purpose of this Pull Request is to fix #154 <issue-number>

### Preview Link

https://pr-157-NEW-YOSHITHA-WEBSITE.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by YoshithaRathnayake** [comment]
Put a comment in the issue as you are working on it @Rishav1707

**Comment by Rishav1707** [comment]
> Put a comment in the issue as you are working on it @Rishav1707

Sorry I missed it once again to comment on the issues.

**Comment by YoshithaRathnayake** [comment]
> > Put a comment in the issue as you are working on it @Rishav1707
> 
> Sorry I missed it once again to comment on the issues.

#153 #154 put the comment like `Shall I work on this?` then I can assign you @Rishav1707

**Review by YoshithaRathnayake — APPROVED** [review]
Thank You! @Rishav1707

**Comment by Rishav1707** [comment]
Your welcome... @YoshithaRathnayake

**Pull request merged**
