### PR TITLE
Alignment of text and image

### LINKED ISSUE #73: Align the about me paragraph with the image
**Describe the bug**
Currently, the paragraph is aligned to down when compare with the image

**To Reproduce**
1. Go to 'WEBSITE'
3. Scroll down to 'About Section'

**Expected behavior**
Align it with the image

**Screenshots**
image

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by mb-008**
## Purpose

The purpose of this Pull Request is to fix #78

## Goals

This will align the text with the image in about section of the website

## Approach

I just made some corrections in the value of bottom margin in the css file of dark folder 

### Screenshots

image

  
### Preview Link

https://pr-78-NEW-YOSHITHA-WEBSITE.surge.sh

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Test environment
 
i have tested the code on ATOM. 

## Learning

I have taken help from Youtube and w3schools for the required work

### CODE REVIEW

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Remove {PR_NUMBER} in preview link and put the pr number to it and update the template

**Comment by mb-008** [comment]
now please merge my pr

**Comment by YoshithaRathnayake** [comment]
> now please merge my pr

Great Job !
Thank You @mb-008

**Review by YoshithaRathnayake — APPROVED** [review]
Great Job !
Thank You @mb-008

**Pull request merged**
