### PR TITLE
location added in contact section

### LINKED ISSUE #85: Add my location to contact section
**Is your feature request related to a problem? Please describe.**
Currently, there is no location mentioned on contact section

**Describe the solution you'd like**
Add a location icon and put like this "Location : Kandy, Sri Lanka"

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by jsvigneshkanna**
## Purpose

The purpose of this Pull Request is to fix #85 

## Goals

To add location in contact section

## Approach

Added location under contact section

### Screenshots

 
image

### Preview Link

https://pr-92-new-yoshitha-website.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
@YoshithaRathnayake , dont label PR as SPAM it will make all hacktoberfest contribution disqualified

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake , dont label PR as SPAM it will make all hacktoberfest contribution disqualified

really sorry so 2 spams right? so I didn't knew about that really sorry, you have one more try to not to get that @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
@YoshithaRathnayake ,

Please try removing SPAM label, that would help much 

Thank you!

**Comment by jsvigneshkanna** [comment]
@YoshithaRathnayake 
Please remove spam label

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Please remove spam label

Sure

**Pull request closed without merging**
