### PR TITLE
Alignment of text and image

### PR DESCRIPTION
**Pull request by mb-008**
The purpose of the pull request is to align the text in centre with respect to that of image in the about section.
The issue no. is #73

### CODE REVIEW

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Add the topics in the pr template. Don't remove them

**Comment by YoshithaRathnayake** [comment]
## Purpose

The purpose of this Pull Request is to fix #<issue-number>

## Goals


## Approach


### Screenshots

  
### Preview Link


https://pr-{PR_NUMBER}-NEW-YOSHITHA-WEBSITE.surge.sh

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

**Comment by YoshithaRathnayake** [comment]
> ## Purpose
> The purpose of this Pull Request is to fix #
> 
> ## Goals
> ## Approach
> ### Screenshots
> ### Preview Link
> [https://pr-{PR_NUMBER}-NEW-YOSHITHA-WEBSITE.surge.sh](https://pr-%7BPR_NUMBER%7D-NEW-YOSHITHA-WEBSITE.surge.sh)
> 
> ## Checklist
> * [x]  This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
> * [ ]  I have read and understood the development best practices guidelines
> * [ ]  My code follows the style guidelines of this project
> * [ ]  I have performed a self-review of my own code
> * [ ]  I have commented my code, particularly in hard-to-understand areas
> * [ ]  I have made corresponding changes to the documentation
> 
> ## Related PRs
> ## Test environment
> ## Learning

This is the template. Don't delete them @mb-008

**Comment by mb-008** [comment]
okaye i will do so as you 
say

**Comment by mb-008** [comment]
@YoshithaRathnayake why you added the spam and invalid label although the fixed the issues you described?

**Comment by mb-008** [comment]
@YoshithaRathnayake Please remove them as these will increase my chances of being disqualified from hacktoberfest

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Please remove them as these will increase my chances of being disqualified from hacktoberfest

Removed spam

**Pull request closed without merging**
