### PR TITLE
Fix age from readme and index.html file

### LINKED ISSUE #111: Change my age in the readme.md file
Change my age in the readme.md file

### PR DESCRIPTION
**Pull request by MRIDUL-MB**
## Purpose

The purpose of this Pull Request is to fix #111

## Goals

Fixing age from readme and index.html file

## Approach

Fixed age from readme and index.html file

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Good job can you remove the Preview Link Section and Screenshot section from this pr template @MRIDUL-MB

**Comment by MRIDUL-MB** [comment]
> Good job can you remove the Preview Link Section and Screenshot section from this pr template @MRIDUL-MB

Sure

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Put the goal of this pr to the Goals Section @MRIDUL-MB

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Add how did you do this pr in the Approach section @MRIDUL-MB

**Review by YoshithaRathnayake — APPROVED** [review]
Good Job !
Thank You @MRIDUL-MB

**Comment by MRIDUL-MB** [comment]
Thanks to You,

**Comment by YoshithaRathnayake** [comment]
> Thanks to You,

Any time

**Pull request merged**
