### PR TITLE
Modified the instagaram link

### LINKED ISSUE #225: Change the instagram profile link in the social media icons section
**Is your feature request related to a problem? Please describe.**
Currently, the link in the instagram icon is wrong

**Describe the solution you'd like**
Change the instagram profile link in the social media icons section

New link - https://www.instagram.com/_yoshitha.r_/

**Are you working on it?**
No (The first one who comment on this issue will be assigned)

# Don't forget to star the repository
# Don't forget to follow me on social media (Visit my GitHub profile for more info)

### PR DESCRIPTION
**Pull request by chow870**
## Purpose

The purpose of this Pull Request is to fix #225 

## Approach

Replaced the correct link link in the  tag

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by chow870** [comment]
@YoshithaRathnayake review the changes and merge the PR

**Review by YoshithaRathnayake — COMMENTED** [review]
Changes are fine!. Make sure you have completed these tasks! @chow870 

- [ ] Starred this repository

- [ ] Followed me on social media (Visit my GitHub profile for more info)

After doing these things I'll merge this for sure

**Comment by chow870** [comment]
@YoshithaRathnayake followed and starred.

**Review by YoshithaRathnayake — APPROVED** [review]
Thanks! @chow870

**Pull request merged**
