### PR TITLE
Updated about section with new content

### LINKED ISSUE #71: Change the about me description
**Is your feature request related to a problem? Please describe.**
Currently, there is a lorem ipsum tag for the about me description

**Describe the solution you'd like**
Change it like this "     Hi, I am **_Yoshitha Rathnayake_**. I am a student and I am 14 years old. I live in **_Kandy_** in **_Sri Lanka_**. I am studing in **_St.Anthony's College Kandy_**. Now, I am in Grade 9D in my school. This is my First Web Site. My favourite subject is **_Information and Communication Technology_**. My mother's name is **_Sudeshika Manthilake_** and my father's name is **_Athula Rathnayake_**. I hope to be a Computer Engineer in the future.     "

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by jsvigneshkanna**
## Purpose

The purpose of this Pull Request is to fix #71 

## Goals

Updated the about-me description in html and meta description tags

## Approach

The changes are done directly to about section in html file

### Screenshots

  
image

### Preview Link

https://pr-72-NEW-YOSHITHA-WEBSITE.surge.sh

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by YoshithaRathnayake** [comment]
put the pr number for {PR_NUMBER} @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
@YoshithaRathnayake Updated the PR, please check now

https://pr-72-new-yoshitha-website.surge.sh/dark/

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Updated the PR, please check now
> 
> https://pr-72-new-yoshitha-website.surge.sh/dark/

Sure

**Comment by YoshithaRathnayake** [comment]
Great Job !
Thank You @jsvigneshkanna

**Review by YoshithaRathnayake — APPROVED** [review]

**Pull request merged**
