### PR TITLE
Instagram icon was added in index.html

### LINKED ISSUE #167: The instagram icon is not loading in the social media icons
- Currently, the instagram icon is not loading in the social media icons
- Add the correct icon `https://img.icons8.com/fluency/48/instagram-new.png`

image

### PR DESCRIPTION
**Pull request by Rishav1707**
## Purpose

The purpose of this Pull Request is to fix #167 <issue-number>

## Goals

- This features will fix the instagram icon loading in the social media icons.

## Approach

- Adding the new png link in the index.html file.

### Before
Screenshot 2022-12-12 184956
### After
Screenshot 2022-12-12 185018

### Preview Link

https://pr-174-NEW-YOSHITHA-WEBSITE.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by YoshithaRathnayake — APPROVED** [review]
Thank You! @Rishav1707

**Comment by YoshithaRathnayake** [comment]
@all-contributors please add @Rishav1707 to the code

**Comment by YoshithaRathnayake** [comment]
@Rishav1707 You have been added to the contribution table of this repository as you put 5 commits for this repository.
Thank You!

**Comment by Rishav1707** [comment]
Thanku @YoshithaRathnayake

**Pull request merged**
